import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <AuthProvider>
        <body className={`${inter.className} bg-gradient-to-b from-transparent to-white dark:from-transparent dark:to-black`}>
          <Navbar/>
          <Toaster />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
